package wrike

// Error - Represents errors generated by wrike
type Error struct {
	ErrorShort, ErrorDescription string
}

func (e Error) Error() string {
	return "Error " + e.ErrorShort + ": " + e.ErrorDescription
}

func checkError(response map[string]interface{}) ([]interface{}, error) {
	if val, ok := response["error"].(string); ok {
		return nil, Error{ErrorShort: val, ErrorDescription: response["error_description"].(string)}
	}

	if val, ok := response["data"].([]interface{}); ok {
		return val, nil
	}

	panic("No data in response")
}

func checkOAuthError(response map[string]interface{}) (string, string, error) {
	if val, ok := response["error"].(string); ok {
		return "", "", Error{ErrorShort: val, ErrorDescription: response["error_description"].(string)}
	}

	accessToken := response["access_token"].(string)
	refreshToken := response["refresh_token"].(string)

	return accessToken, refreshToken, nil
}
